### ISSUE TITLE
Startup Apps

### ISSUE THREAD

**Issue by barxilly** [MistyKnives/Kick-Discord-RPC#11]
Hi, I was wondering if you could add a feature in the config to add to startup apps. I've done it manually but ik some people will want it but can't go through the trouble.

It should be as easy as creating a shortcut to the application in %appdata%\Microsoft\Windows\Start Menu\Programs\Startup

I'd create a pull request and help, but Java scares me...

**Comment by tyyzf** [comment]
Hello,
Thank you for the suggestion. At the moment by the very late reply you can see I am not currently maintaining this project.

Will look into this in the future if I continue maintaining this otherwise I do apologise.

Thank you!
