### ISSUE TITLE
Not Displaying/Out Of Date

### ISSUE THREAD

**Issue by YLRTMusic** [MistyKnives/Kick-Discord-RPC#12]
I have been trying to use this application for about an hour now, i cant seem to get it to display on my profile, I get a notification (The only notification that comes up) saying, Header: Java(TM) Platform SE Binary ---- (Out Of Date) is no longer supported, Please consider updating, and i cant figure out what im doing wrong, ive tried just using flat out java 20, and java 20.0.2 and neither work, i cant seem to get it to work period. thanks a lot if you can help with this.

**Comment by tyyzf** [comment]
Hello,
Sorry for the late reply. I am not maintaining this project at the moment so I have not been reading the issues.

First of all, the out of date message. Ignore that. That is me messing up a line of code that I did not update before release. Don't worry as long as you're using the latest version you'll be fine.

Secondly, with the java issue. 
 - Is there any errors that pop up? 
 - does the program start?
 - does the program at least popup on the task manager for x amount of time?
 - Have you attempted to recompile the project into a jar and run it via the jar?

Please let me know how this goes. Thank you!

**Comment by tyyzf** [comment]
https://github.com/MistyKnives/Kick-Discord-RPC/releases/tag/4.0.2

I have updated v4.0.2 with new code which i hope will work better for you. give it a try and let me know how it goes!

**Comment by YLRTMusic** [comment]
Thanks for the reply! 

i get no errors or pop ups other than what i shared in the issue pull above, 

program seems to be running as expected though i see no rpc in discord, 

I havent seen any popups on task manager, 

I will give it a shot, although im not certain on how to do this :)

so my guess is it could be an issue with the connection to either, my kick channel, or to discord. neither of which i know how to solve.

**Comment by tyyzf** [comment]
Hello,
May you provide your kick username and also any errors that has happened since running the new update?

Thank you.
