### ISSUE TITLE
Mine will not launch

### ISSUE THREAD

**Issue by bigbadbali** [MistyKnives/Kick-Discord-RPC#4]
When I tried to open it, the prompt gave me an error and an error report
[hs_err_pid28176.log](https://github.com/MistyKnives/Kick-Discord-RPC/files/11496528/hs_err_pid28176.log)

**Comment by tyyzf** [comment]
I am currently working on this issue, stay tuned for v4.0.0, it will fix this. issue will stay open until then.

**Comment by tyyzf** [comment]
v4.0.0 will be releasing in a few minutes. closing due to bug will no longer happen. I hope you like v4.0.0!
