### ISSUE TITLE
VirusTotal

### ISSUE THREAD

**Issue by WannaBeChay** [MistyKnives/Kick-Discord-RPC#6]
https://www.virustotal.com/gui/file/016b1abc690b1ecbb466d8a341e0fc5cacec28efb5a32d1ff3b4faa9a5a3f426

Trojan.PSW.Worgtop.ak --> Trojan-PSW programs are grabbers normaly (steal info)

**Comment by tyyzf** [comment]
i build the source that is visible on this Github into a jar, then i use launch4j to compile it into an exe. I dont put viruses into it so think what you want but i'm honest with my work. i dont need anyones info

**Comment by tyyzf** [comment]
feel free to contact me on discord "mistyknives" (no hashtag) if you need more proof.

**Comment by tyyzf** [comment]
https://github.com/MistyKnives/Kick-Discord-RPC/blob/main/docs/build.md

building from .jar to .exe exactly. any virus

talks about false positives with launch4j: https://sourceforge.net/p/launch4j/discussion/332683/thread/e75e5ed9/
