### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by pelicanfuture** [MistyKnives/Kick-Discord-RPC#8]
Could you please make a Linux version of this app? Or at least make it so it's just a .jar file so it can be run on any system that has java installed? I could help with the porting if you need it.

**Comment by tyyzf** [comment]
Hello!
Apologises for the late reply. I can see what I can do for you as there will be some issues with running it on linux such as notifications, etc. let me have a look into it then I will get back to you.

Thank you.

**Comment by pelicanfuture** [comment]
Ok thanks!

**Comment by tyyzf** [comment]
closing for now, will look into this in the future if i continue this project.

Thank you for the suggestion!
