### ISSUE TITLE
Processing Request Error

### ISSUE THREAD

**Issue by themalchim** [MistyKnives/Kick-Discord-RPC#9]
![image](https://github.com/MistyKnives/Kick-Discord-RPC/assets/141016228/9389c9c3-9bfb-4336-85cd-977153dad2f0)

**Comment by LYRYCAL** [comment]
> ![image](https://user-images.githubusercontent.com/141016228/257160667-9389c9c3-9bfb-4336-85cd-977153dad2f0.png)

Yeah i got the same problems.

**Comment by tyyzf** [comment]
Hello,
Apologises for the very late reply. This error happens because you have changed the Discord Client ID. 

You must only change this if it is an Application ID, not your own account ID.

Please reset the ID back to 1099615872777195530 and try again.

thank you.
